# Generated by Django 5.1.2 on 2024-11-01 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('desenvolvedora', models.CharField(max_length=50)),
                ('data_lancamento', models.DateField()),
                ('classificacao_metacritic', models.SmallIntegerField()),
                ('tags', models.JSONField(default=list)),
                ('plataforma', models.JSONField(default=list)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.FileField(upload_to='jogos')),
                ('disponivel_venda', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='api.categoria')),
            ],
        ),
    ]
