# Generated by Django 5.1.2 on 2024-11-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='jogos'),
        ),
    ]
