# Generated by Django 5.1.2 on 2024-11-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_jogo_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='jogos'),
        ),
    ]
