# Generated by Django 5.1.2 on 2024-11-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_jogo_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='plataforma',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='tags',
            field=models.CharField(max_length=300),
        ),
    ]
